### ISSUE TITLE
source map support?

### ISSUE THREAD

**Issue by aaronjensen** [webpack-contrib/mocha-loader#19]
Is it possible to get source maps working in the browser? I see line numbers, but file names report as <anonymous>.

This is with `eval-source-map`. With `inline-source-map` it doesn't work at all.

```
  at Context.eval (eval at <anonymous> (specs.js:3992:2), <anonymous>:35:11)
```

**Comment by noirbizarre** [comment]
I'm really interested in this too.
Withtout sourcemap support, debugging failing tests is really hard !

**Comment by amir-arad** [comment]
same here

**Comment by chemzqm** [comment]
The only devtool option that can get line number is ` eval`

**Comment by amir-arad** [comment]
but eval has some serious modules bugs in some projects

**Comment by chemzqm** [comment]
I can make correct file name and line number shown by changing this https://github.com/evanw/node-source-map-support a bit.  It's basically a hack of  `Error.prepareStackTrace`.  Unfortunately, this one only works for devtool `source-map` and `inline-source-map`.

 The `<anonymous>` filename looks like a bug of v8, as it's would never parse file name from `//@ sourceMappingURL=data:application/json;base64,`  https://code.google.com/p/v8/source/browse/trunk/src/messages.js#590

**Comment by chemzqm** [comment]
https://github.com/chemzqm/stack-source-map attamp to make the error stack works with all souce-map options of wepack, Chrome only

**Comment by michael-ciniawsky** [comment]
Closing in favor of #36
