### ISSUE TITLE
Best way to set the UI?

### ISSUE THREAD

**Issue by Levino** [webpack-contrib/mocha-loader#54]
I want to use the TDD ui. Where is the best point to set it? So far I use the way from https://github.com/webpack/mocha-loader/issues/18#issuecomment-130544540 Which feels rather clumsy. How about a "mochaOptions" field in the webpack.config.js?

**Comment by sleexyz** [comment]
+1 for mochaOptions field

**Comment by sleexyz** [comment]
@Levino It's not documented at all, but this line of code reveals that there's a query option to switch the UI. 
https://github.com/webpack-contrib/mocha-loader/blob/master/index.js#L12

so something like this:
```js
'mocha-loader?ui=tdd!./test.js'
```
( as a webpack-resolved path)

**Comment by TheLarkInn** [comment]
@webpack-contrib/admin-team lets doc this. <3

**Comment by bebraw** [comment]
@sleexyz The other reporters seem more or less useless in web. The currently enabled one is the only one that does not emit to the console. `ui=tdd` is broken (complains about `describe`) unless you perform some extra setup.

**Comment by Levino** [comment]
FWIW: I am using karma now which is much easier. Does not need mocha-loader and comes with a fully fledged test runner.

**Comment by bebraw** [comment]
@Levino Yeah, I agree Karma is sweet after you get past the initial setup. More flexible runner for sure.

**Comment by michael-ciniawsky** [comment]
Closing in favor of #65
