### ISSUE TITLE
Karma alternative?

### ISSUE THREAD

**Issue by tarjei** [webpack-contrib/mocha-loader#61]
Hi, is it possible to integrate mocha-loader and chrome --headless to be able to drop using karma for tests?

Do you guys have any idea what would be required to do something like that?

**Comment by vietnogi** [comment]
yea, i dropped karma and simply use webpack + mocha loader, checkout this article http://randycoulman.com/blog/2016/03/22/testing-with-mocha-and-webpack/

**Comment by d3viant0ne** [comment]
Another completely viable and imho preferable option is to just use Jest.
