### ISSUE TITLE
Support Mocha 4 as a peer dependency

### ISSUE THREAD

**Issue by bebraw** [webpack-contrib/mocha-loader#66]
Currently the loader doesn't support Mocha 4 (only up to 3) and will complain about the peer dependency.

**Comment by michael-ciniawsky** [comment]
Did you test it with `mocha >= v4.0.0` or was there anything breaking the loader during the major bump ?

**Comment by bebraw** [comment]
My project is too simple to say anything conclusive but Mocha 4 seemed just to work. I don't know what caused the SemVer bump. Maybe some API changed.

**Comment by michael-ciniawsky** [comment]
Quick PR fixing the `peerDependency` range 🙃  ?

**Comment by bebraw** [comment]
No time at the moment. Someone would have to have a peek at their changelog and figure out what changed exactly.

**Comment by tilgovi** [comment]
Seems pretty compatible: https://boneskull.com/mocha-v4-nears-release/
