### ISSUE TITLE
[Bug] (WDS) Cannot add property files, object is not extensible

### ISSUE THREAD

**Issue by ctaylo21** [webpack-contrib/mocha-loader#67]
I am getting the error ` Cannot add property files, object is not extensible` when trying to use the mocha-loader module with the webpack-dev-server. I'm running the following command via CLI:

```./node_modules/webpack-dev-server/bin/webpack-dev-server.js 'mocha!./test.js' --output-filename test.js```

and test.js is just a basic file:

```
var assert = require('assert')
describe('test', () => {
  it('should be true', () => {
    assert(true)
  })
})
```

Versions:
`mocha: ^4.0.1`
`mocha-loader": "^1.1.1`
`webpack-dev-server": "^2.9.4`

The error is occurring inside of `node_modules/mocha/lib/mocha.js` as soon as it hits
```
function Mocha (options) {
  options = options || {};
  this.files = []; // fails here
```

Any ideas?

**Comment by eflo11** [comment]
I've ran into this issue as well. Is there anyway around this issue?

**Comment by evilebottnawi** [comment]
@eflo11 @ctaylo21 can you create minimum reproducible test repo?

**Comment by ctaylo21** [comment]
I got around this by just using an HTML file that manually loaded mocha and the test bundle and executed it. I'm honestly still not 100% sure what this loader does or when I should use it. The repo to create would be very simple but it could just be that I'm using it wrong.

Just a package.json with the above mentioned dependencies (plus webpack) and a single test file. Then just run `./node_modules/webpack-dev-server/bin/webpack-dev-server.js 'mocha!./test.js' --output-filename test.js` and you will see error. Once again, it could be because of my lack of understanding of how to use this.

**Comment by pendenaor** [comment]
i've ran into this same issue, and i've to replace `mocha!` to `mocha-loader!` to fix it.
