### ISSUE TITLE
Patch-release this npm package

### ISSUE THREAD

**Issue by astorije** [webpack-contrib/mocha-loader#69]
Hi there! Sorry to open an issue for this, but any chance a release could be made?

[One of my open PRs](https://github.com/thelounge/lounge/pull/1726) for [The Lounge](https://github.com/thelounge/lounge) is currently blocked by a bug that was fixed and merged at https://github.com/webpack-contrib/mocha-loader/pull/68. I could confirm [with a bit of `package.json` hackery](https://github.com/thelounge/lounge/pull/1726/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R85) that this fixes the issue, but we can't merge until this fixes makes it into an npm release.

Sorry if this is not the right way to ping you, but I left a comment in PR and asked on the Gitter channel before spamming here :)

Thank you very much for your efforts!! 🙏

**Comment by michael-ciniawsky** [comment]
[`v1.1.2`](https://github.com/webpack-contrib/mocha-loader/releases/tag/v1.1.2) 🎉
