### ISSUE TITLE
Mocha 5.0 not working with mocha-loader

### ISSUE THREAD

**Issue by patrickptm** [webpack-contrib/mocha-loader#71]
I have tried to install mocha-loader, but I get the error:
peer invalid The package mocha@5.0.0 does not satisfy its siblings' peer Dependencies requirements!
 
Does that mean that mocha-loader is not working with the latest version of mocha?
If it's not working, can someone explain how can I load my mocha test files using webpack? I'm struggling to find the right webpack.config file. My aim is to load my mocha test files using webpack and run them in the browser.

**Comment by evilebottnawi** [comment]
@patrickptm we already have PR https://github.com/webpack-contrib/mocha-loader/pull/70, let's wait approve and publish new version :+1: Thanks for issue!
