### ISSUE TITLE
Is mocha bundled when using mocha-loader?

### ISSUE THREAD

**Issue by patrickptm** [webpack-contrib/mocha-loader#72]
I am using mocha-loader in the following webpack config:

```
            {
                test: /test\.js$/,
                use: 'mocha-loader',
                exclude: /node_modules/,
            }
```
In my index.js, I am importing my tests:
```
import testAp1 from '../../test/Ap1-test';
import testAp2 from '../../test/Ap2-test';
import testAp3 from '../../test/Ap3-test';
import testAp4 from '../../test/Ap4-test';
```

Using webpack-bundle-size analyzer, I am observing that mocha gets bundled, which significantly increases my bundle size ( 700kB at the moment for a simple SPA - out of which 30% is mocha). My aim is to run mocha tests in browser in a React application.

Is that the way mocha-loader is supposed to work: bundling mocha? Is there a way I can avoid bundling it? (loading it via CDN but still be able to run it in bundled context?).

**Comment by ooflorent** [comment]
`mocha-loader` adds `require("mocha")`. So yes, it is bundled. I guess you could use `externals` inside your webpack config to prevent this.
