### ISSUE TITLE
TS2307: Cannot find module node_modules/mocha-loader/dist/EnhancedMocha.js

### ISSUE THREAD

**Issue by fsproru** [webpack-contrib/mocha-loader#89]
- Operating System: macOS Catalina
- Node Version: v10.15.2
- NPM Version: 6.4.1, we're using Yarn 1.15.2
- webpack Version: 4.41.6
- mocha-loader Version: 4.0.1

### Expected Behavior

Tests run as a part of the webpack

### Actual Behavior

Getting a compilation error, tests don't run in webpack but run using the standalone mocha binary

### Code

```js
// webpack.config.js
const slsw = require('serverless-webpack');
module.exports = {
  mode,
  entry: slsw.lib.entries,
  resolve: {
    plugins: [new TsconfigPathsPlugin()],
    extensions: [
      '.js',
      '.ts',
    ]
  },
  output: {
    libraryTarget: 'commonjs2',
    path: path.join(__dirname, '.webpack'),
    filename: '[name].js',
  },
  stats: {
    modules: true,
    colors: false,
  },
  target: 'node',
  module: {
    rules: [{
      test: /\.ts$/,
      use: [{
        loader: 'ts-loader'
      }],
    }, {
      test: /test\.ts$/,
      use: [{
        loader: 'mocha-loader'
      }],
      exclude: /node_modules/,
    }]
  },
  plugins: [
    new ProgressPlugin({profile: false}),
  ],
};
```

### How Do We Reproduce?

Create a new project with serverless, serverless-webpack and mocha-loaded with the tests written in Typescript. Run `sls package`, see the error.

**Comment by AviVahl** [comment]
I played around with `mocha-loader` and `target: 'node'`. It's broken.

`EnhancedMocha.js` calls `require()` with a variable as an argument (which `webpack` cannot resolve and warns about).

Other than that issue, the `mocha` package itself, or at least the part used by the `target: 'node'` flow (`mocha/lib/mocha.js`), doesn't appear to be bundle-compatible. `mocha` made package changes to support node in native esm mode, and I get bunch of bundling errors from there (again `Critical dependency: the request of a dependency is an expression` which means require is called with a variable).

There were never any tests for the `target: 'node'` flow, so I think it's safe to assume this broke with recent mocha releases.

Now for the real question: if I want to run my tests in node using mocha, why not just use the mocha CLI (or programmatic api)? Does it even make sense to *want to* bundle mocha *itself* for node execution?

I see no way mocha-loader can give value to node-based tests unless mocha itself is bundle-compatible. Maybe this calls to remove that broken code and replace it with an error message? (@evilebottnawi I wonder what you think...) 

It should be noted that I can always bundle my spec files with `target: 'node'`, but without `mocha-loader`. I can later execute that bundle using the mocha cli: `mocha dist/test.node-bundle.js`.
